const throwError = (value) => {
  throw new Error(`[ERROR] ${value}`);
};
